name: deploy documentation

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  docs:
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: install dependencies
        run: uv sync --locked --all-extras --dev

      - name: enable github problem matcher
        uses: sphinx-doc/github-problem-matcher@master

      - name: create tmp directory
        run: mkdir -p /tmp/dovedocs

      - name: sphinx build
        run: uv run sphinx-build -b html "docs/source" "/tmp/dovedocs"

      - name: setup pages
        uses: actions/configure-pages@v5
        if: ${{ github.repository == 'idaholab/DOVE' && github.ref_type == 'tag' }}

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        if: ${{ github.repository == 'idaholab/DOVE' && github.ref_type == 'tag' }}
        with:
          path: "/tmp/dovedocs"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        if: ${{ github.repository == 'idaholab/DOVE' && github.ref_type == 'tag' }}
